### ISSUE TITLE
Cannot read property 'Store' of undefined

### ISSUE THREAD

**Issue by estvmachine** [patriksimek/connect-mssql#3] opened 2015-05-20 13:12 UTC
I got this error

![image](https://cloud.githubusercontent.com/assets/2062668/7726376/9925d7aa-fecf-11e4-9a1f-b3099aeab163.png)

This is my code:

```javascript
var express = require('express'),
     	session = require('express-session'),
       MSSQLStore=require('connect-mssql'),
       passport = require('passport');

	var configDB = {
			    user: 'random',
			    password: 'randomerp',
			    server: '192.168.20.200',
			    database:'9654490MM',
			    stream: true,
			    connectionTimeout: 60000,
			    requestTimeout : 60000,

			    pool: {
			        max: 10,
			        min: 0,
			        idleTimeoutMillis: 30000
			    },
			    options: {
			        tdsVersion: '7_1',
			        encrypt: true // Use this if you're on Windows Azure
			    }
			},
      optionsDB= {
				table: 'SESSIONS'
		};

module.exports = function() {
	var app = express();
      app.use(bodyParser.urlencoded({
		extended: true
	}));
	app.use(bodyParser.json());
     app.use(cookieParser());


 //Using MSSQLStore
       app.use(session({
		//secret: config.sessionSecret,
		store: new MSSQLStore(configDB,optionsDB)
	}));

	// use passport session
	app.use(passport.initialize());
       app.use(passport.session());

	// connect flash for flash messages
	app.use(flash());

   ....

   return app;
}

```

**Comment by estvmachine** [comment] 2015-05-20 13:27
I try this way

```javascript
var express = require('express'),
        session = require('express-session'),
       MSSQLStore=require('connect-mssql')({
               session:session
     }),
       passport = require('passport');

    var configDB = {
                user: 'random',
                password: 'randomerp',
                server: '192.168.20.200',
                database:'9654490MM',
                stream: true,
                connectionTimeout: 60000,
                requestTimeout : 60000,

                pool: {
                    max: 10,
                    min: 0,
                    idleTimeoutMillis: 30000
                },
                options: {
                    tdsVersion: '7_1',
                    encrypt: true // Use this if you're on Windows Azure
                }
            },
      optionsDB= {
                table: 'SESSIONS'
        };

module.exports = function() {
    var app = express();
      app.use(bodyParser.urlencoded({
        extended: true
    }));
    app.use(bodyParser.json());
     app.use(cookieParser());

    // Using the MSSQLStore 
         app.use(session({
		saveUninitialized: true,
		resave: true,
		secret: 'keyboardcat',
		store: new MSSQLStore(configDB,optionsDB)
	}));

    // use passport session
    app.use(passport.initialize());
       app.use(passport.session());

    // connect flash for flash messages
    app.use(flash());

   ....

   return app;
}
```

**Comment by patriksimek** [comment] 2015-05-20 15:13
You should do your requires like this:
```javascript
var express = require('express'),
    session = require('express-session'),
    MSSQLStore = require('connect-mssql')(session),
    passport = require('passport');
```

**Comment by estvmachine** [comment] 2015-05-20 15:32
Works with that solution!.

Now i got other error..maybe you can help me. This plugin is for using with 'passport' so i try define  my local strategy like a connection to SQL Server using node-mssql plugin with tedious driver (https://github.com/patriksimek/node-mssql).

When i try with this two options i got this

![image](https://cloud.githubusercontent.com/assets/2062668/7728889/b7144f52-fedf-11e4-9d69-f89e9f725963.png)

 **ROUTES OPTION 1**

```javascript
//Option 1
module.exports = function(app) {
  	app.post('/auth/signin',passport.authenticate('local',{ session: false }),
			function(req, res) {
					console.log(req.user);
				res.json(req.user.username);
	});
}
```


 **ROUTES OPTION 2**

```javascript
//Option 2
module.exports = function(app) {
      app.post('/auth/signin', function(req, res,next){

		passport.authenticate('local', function(err, user, info) {

		//if (err || !user) {
		if(err !== null){
			res.status(400).send(info);
		} else {
			// Remove sensitive data before login
			user.password = undefined;
			user.salt = undefined;
			user.displayName= user.username;

			/*req.user=user;
			res.json(user);*/

			//Esto produce que se guarde una sesion, ademas de guardar req.user=user
			req.login(user, function(err) {
				if (err) {
					res.status(400).send(err);
				} else {
					res.json(user);
				}
			});
		}
	})(req, res, next);
  });
}
```

**STRATEGY**

```javascript

//File: strategies/local.js

module.exports = function() {

passport.use(new LocalStrategy(
		{
			usernameField: 'username',
			passwordField: 'password',
      passReqToCallback: true
		},
		function(req, username, password, done) {

				sql.connect(configDB, function(err) {
		        // ... error checks

		       var request = new sql.Request();
		        request.query('SELECT username AS username,password AS password FROM USERS WHERE username= '+ "'"+ username+"'");

		        request.on('recordset', function(columns) {
		        // Emitted once for each recordset in a query
		            columnas.push(columns);
		        });

		        request.on('row', function(row) {
		            // Emitted for each row in a recordset
		            filas.push(row);
		        });

		        request.on('error', function(err) {
		            // May be emitted multiple times
		            errores.push(err);
		        });

		        request.on('done', function(returnValue) {
		            // Always emitted as the last one
		            //console.tag('controllers/drivers/mssql','executeQuery','columnas').log(columnas);
		            console.tag('config/strategies/mssql.js','LocalStrategy','filas').log(filas);
		            console.tag('config/strategies/mssql.js','LocalStrategy','errores').log(errores);

								if(errores.length!==0){
									var user= filas[0];
									return done(null, user);
								}
								else {
									return done(null,false, {message: 'Error de conexion'} )
								}
								
		        });

		    });//fin sql.connect


	    } // fin function(username, password, done)

	));
};

```

**MIDDLEWARE**
```javascript

var express = require('express'),
       session = require('express-session'),
       bodyParser = require('body-parser'),
       cookieParser = require('cookie-parser'), 
       passport = require('passport'),
       MSSQLStore=require('connect-mssql')(session),
       	flash = require('connect-flash');
    
//Configure mssql driver
var configDB = {
			    user: 'random',
			    password: 'randomerp',
			    server: '192.168.20.200',
			    database:'9654490MM',
			    options: {
			        encrypt: true // Use this if you're on Windows Azure
			    }
			},
		optionsDB= {
				table: 'sessions'
		};

  app.use(express.static(path.resolve('./public')));
  app.use(express.cookieParser());
  app.use(express.bodyParser());
   app.use(session({
		saveUninitialized: true,
		resave: true,
		secret: config.sessionSecret,
		store: new MSSQLStore(configDB,optionsDB)
	}));
  app.use(passport.initialize());
  app.use(passport.session());
  app.use(flash());
 
 //Now i tell the app, where the routes and strategies are
  require('../routes/users.routes.js')(app);
  require(path.resolve('./strategies/local.js))();
  ...
  app.listen(8080);
});

```

**Comment by patriksimek** [comment] 2015-05-20 15:57
There is at least one callback that isn't property executed. From biref look I can't see which one. You should trace you'r code to see what part of it is not reached by the interpret.

**Comment by estvmachine** [comment] 2015-05-20 16:03
This works, so is a problem with  the node-mssql, i 

```javascript
passport.use(new LocalStrategy(
        {
            usernameField: 'username',
            passwordField: 'password',
      passReqToCallback: true
        },
        function(req, username, password, done) {


                        var user={};
                            user.username='stev';
                                user.password='12345678';
                                user.displayName='EstebanCampos'

                        return done(null, user);

        } // fin function(username, password, done)

    )); // fin passport.use(...)

```

This is the method i use for access SQL Server, how you do it?, i mean a way that you know its work to connect SQL Server with node-mssql, this works for me with others queries...

```javascript
sql.connect(configDB, function(err) {
		        // ... error checks

		       var request = new sql.Request();
		        request.query('SELECT username AS username,password AS password FROM USERS WHERE username= '+ "'"+ username+"'");

		        request.on('recordset', function(columns) {
		        // Emitted once for each recordset in a query
		            columnas.push(columns);
		        });

		        request.on('row', function(row) {
		            // Emitted for each row in a recordset
		            filas.push(row);
		        });

		        request.on('error', function(err) {
		            // May be emitted multiple times
		            errores.push(err);
		        });

		        request.on('done', function(returnValue) {
		            // Always emitted as the last one
		            //console.tag('controllers/drivers/mssql','executeQuery','columnas').log(columnas);
		            console.tag('config/strategies/mssql.js','LocalStrategy','filas').log(filas);
		            console.tag('config/strategies/mssql.js','LocalStrategy','errores').log(errores);

								if(errores.length!==0){
									var user={};
											user= filas[0];
									    user.username='stev';
											user.password='12345678';
											user.displayName='EstebanCampos';

									return done(null, user);
								}
								else {
									return done(null,false, {message: 'Error de conexion'} )
								}

							  /*if(!hash.isValid(user.password,password))   {
										console.error('Usuario desconocido o contraseña invalida');
										return done(null, false, {
										message: 'Usuario desconocido o contraseña invalida'
									});
									}
									else{
											return done(null, user);
									}*/
		          });

		    });
```

**Comment by patriksimek** [comment] 2015-05-20 18:57
Closing, duplicate of https://github.com/patriksimek/node-mssql/issues/165.

**Closed by patriksimek** 2015-05-20 18:57 UTC
